### ISSUE TITLE
Use non existing class

### ISSUE THREAD

**Issue by DnD-Mimosa** [DivanteLtd/magento2-vsbridge-indexer-msi#3]
Hi !

The class `Divante\VsbridgeIndexerMsi\Model\LoadInventory` implements the interface `Divante\VsbridgeIndexerCatalog\Api\LoadInventoryInterface` but this one doesn't exists.

Can you create this one or remove the implementation please ?

Thank you !

BR,
Florian.

**Comment by pkarw** [comment]
@DnD-Mimosa does it mean it's been solved so you closed thisone? :)

**Comment by DnD-Mimosa** [comment]
Hi @pkarw !

Yes it was my fault, I had to upgrade the basse indexer module x)

You may have to update the `composer.json` to specify the minimum version required of vsf bridge to prevent this case 😉 

BR,
Florian.
